routes/web.php
<?php

Route::get('/', 'ArticleController@index')->name('home');

Route::get('register', 'RegisterController@showForm')->name('register');
Route::post('register', 'RegisterController@register');
Route::get('login', 'LoginController@showForm')->name('login');
Route::post('login', 'LoginController@login');
Route::get('logout', 'LoginController@logout')->name('logout');

Route::resource('article', 'ArticleController');
Route::get('profile/edit', 'ProfileController@edit')->name('profile.edit');
Route::put('profile', 'ProfileController@update')->name('profile.update');
Route::get('profile/{user}', 'ProfileController@show')->name('profile.show');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Article;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::latest()->paginate(5);

        return view('article.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('article.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (!session('email')) {
            return redirect()->route('login');
        }

        $path = null;

        if ($request->hasFile('image')) {
            $path = $request->file('image')->store('images');
        }
        $userId = session('id');

        $article = DB::insert("INSERT INTO
                        `articles` (user_id,title,image,body,created_at,updated_at)
                        VALUES (?,?,?,?,?,?)",[
                        $userId, $request->title,$path,$request->body,now(),now()
                    ]);

        return redirect()->route('article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = DB::table('articles')
                        ->select('articles.*', 'users.name')
                        ->join('users', 'articles.user_id', 'users.id')
                        ->whereRaw('articles.id = ' .$id)
                        ->first();

        return view('article.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('article.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!session('email')) {
            return redirect()->route('login');
        }

        $article = DB::table('articles')
                        ->select('articles.*', 'users.name')
                        ->join('users', 'articles.user_id', 'users.id')
                        ->whereRaw('articles.id = ' .$id)
                        ->first();

        $path = $article->image;

        if ($request->hasFile('image')) {
            $path = $request->file('image')->store('images');
        }

        $userId = session('id');

        $article = DB::update("UPDATE
                        `articles` SET user_id=?,title=?,image=?,body=?,updated_at=? WHERE id=?",[
                        $userId, $request->title,$path,$request->body,now(),$id
                    ]);

        return redirect()->route('article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();

        return redirect()->route('article.index');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class LoginController extends Controller
{
    public function showForm()
    {
        if (session('email')) {
            return redirect('/');
        }

        return view('auth.login');
    }

    public function login(Request $request)
    {
        $user = DB::table('users')
                    ->select('id','name','email')
                    ->where('email', $request->email)
                    ->where('password', md5($request->password))
                    ->first();

        session((array) $user);

        return redirect('/');
    }

    public function logout(Request $request)
    {
        $request->session()->flush();

        return redirect()->route('home');
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class ProfileController extends Controller
{
    public function show($id)
    {
        $user = DB::table('users')
            ->select('*')
            ->whereRaw('users.id = ' .$id)
            ->first();

        $articles = DB::table('articles')
            ->select('*')
            ->join('users', 'articles.user_id', 'users.id')
            ->whereRaw('user_id = ' .$id)
            ->get();

        return view('user.show', compact('user', 'articles'));
    }

    public function edit()
    {
        $user = DB::table('users')
            ->select('*')
            ->whereRaw('users.id = ' . session('id'))
            ->first();

        return view('user.edit', compact('user'));
    }

    public function update(Request $request)
    {
        $user = DB::table('users')
            ->select('*')
            ->whereRaw('users.id = ' . session('id'))
            ->first();

        DB::update("UPDATE
            `users` SET name=?,email=?,password=?,updated_at=? WHERE id=?",[
            $request->name,$request->email,$user->password ?? $request->password,now(),session('id')
        ]);

        return back();
    }
}

app/Http/Controllers/RegisterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use DB;

class RegisterController extends Controller
{
    public function showForm()
    {
        if (session('email')) {
            return redirect('/');
        }

        return view('auth.register');
    }

    public function register(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email|unique:users,email',
            'password' => 'required'
        ]);

        $register = DB::insert("INSERT INTO users (name,email,password) VALUES (?,?,?)", [
            $request->name,$request->email,md5($request->password)
        ]);

        if ($register) {
            $user = DB::table('users')->select('id','name','email')->where('email', $request->email)->first();

            session((array) $user);

            return redirect('/');
        }
    }
}

resources/views/article/create.blade.php
@extends('templates.default')

@section('masthead')
    @component('templates.components._masthead', [
        'image' => asset('assets/img/contact-bg.jpg'),
        'title' => 'Register',
        'subtitle' => 'Create an account & Share your article'
    ])

    @endcomponent
@endsection

@section('content')
    <p>Publish your Article</p>
    <form action="{{ route('article.store') }}" name="sentMessage" id="registerForm" method="post" enctype="multipart/form-data">
        @csrf
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Title</label>
                <input type="text" name="title" class="form-control" placeholder="Your title" id="title" required data-validation-required-message="Please enter your title." value="{{ old('title') }}">
                @if ($errors->has('title'))
                    <p class="help-block text-danger">{{ $errors->first('title') }}</p>
                @endif
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Title</label>
                <input type="file" name="image" class="form-control" placeholder="Your image" id="image" data-validation-required-message="Please enter your title.">
                {{-- @if ($errors->has('title'))
                    <p class="help-block text-danger">{{ $errors->first('title') }}</p>
                @endif --}}
            </div>
        </div>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <label>Description</label>
            <textarea name="body" id="" cols="30" rows="5" class="form-control" placeholder="Write your content here...">{{ old('body') }}</textarea>
            @if ($errors->has('email'))
              <p class="help-block text-danger">{{ $errors->first('email') }}</p>
            @endif
          </div>
        </div>
        <br>
        <div id="success"></div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary" id="">Save</button>
        </div>
    </form>
@endsection

resources/views/article/edit.blade.php
@extends('templates.default')

@section('masthead')
    @component('templates.components._masthead', [
        'image' => asset('assets/img/contact-bg.jpg'),
        'title' => 'Register',
        'subtitle' => 'Create an account & Share your article'
    ])

    @endcomponent
@endsection

@section('content')
    <p>Publish your Article</p>
    <form action="{{ route('article.update', $article) }}" name="sentMessage" id="registerForm" method="post" enctype="multipart/form-data">
        @csrf
        @method("PUT")
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Title</label>
                <input type="text" name="title" class="form-control" placeholder="Your title" id="title" required data-validation-required-message="Please enter your title." value="{{ $article->title ?? old('title') }}">
                @if ($errors->has('title'))
                    <p class="help-block text-danger">{{ $errors->first('title') }}</p>
                @endif
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Title</label>
                <input type="file" name="image" class="form-control" placeholder="Your image" id="image" data-validation-required-message="Please enter your title.">
                {{-- @if ($errors->has('title'))
                    <p class="help-block text-danger">{{ $errors->first('title') }}</p>
                @endif --}}
            </div>
        </div>
        <div class="control-group">
          <div class="form-group floating-label-form-group controls">
            <label>Description</label>
            <textarea name="body" id="" cols="30" rows="5" class="form-control" placeholder="Write your content here...">{{ $article->body ?? old('body') }}</textarea>
            @if ($errors->has('email'))
              <p class="help-block text-danger">{{ $errors->first('email') }}</p>
            @endif
          </div>
        </div>
        <br>
        <div id="success"></div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary" id="">Update</button>
        </div>
    </form>
@endsection

resources/views/article/index.blade.php
@extends('templates.default')

@section('masthead')
    @component('templates.components._masthead', [
        'image' => asset('assets/img/contact-bg.jpg'),
        'title' => 'List of Articles',
        'subtitle' => 'Best article for you'
    ])

    @endcomponent
@endsection

@section('content')
    @foreach ($articles as $article)
        <div class="post-preview">
            <a href="{{ route('article.show', $article) }}">
                <h2 class="post-title">
                    {{ $article->title }}
                </h2>
                <h3 class="post-subtitle">
                    {{ str_limit($article->body, 100)}}
                </h3>
            </a>
            <p class="post-meta">Posted by
            <a href="{{ route('profile.show', $article->user) }}">{{ $article->user->name }}</a>
            on {{ $article->created_at }}</p>
        </div>
        @if ($article->user_id === session('id'))
        <div class="row">
            <a href="{{ route('article.edit', $article) }}" class="btn btn-warning">Edit</a>
            <button id="delete" href="{{ route('article.destroy', $article) }}" class="btn btn-danger">Delete</button>
        </div>
        @endif
        <hr>
        <form action="" id="deleteForm" method="post">
            @csrf
            @method("DELETE")
            <input type="submit" value="" style="display:none">
        </form>
    @endforeach
@endsection

@push('scripts')
<script>



    $('button#delete').on('click', function() {
        var href = $(this).attr('href');

        document.getElementById('deleteForm').action = href;
        document.getElementById('deleteForm').submit();
    });
</script>
@endpush

resources/views/article/show.blade.php
@extends('templates.default')

@section('masthead')
    @component('templates.components._masthead', [
        'image' => asset('assets/uploads/'.$article->image),
        'title' => $article->title,
        'subtitle' => ''
    ])
        <span class="meta">Posted by
                <a href="#">
                    {{ $article->name }}
                </a>
                on
                {{ $article->created_at }}
        </span>
    @endcomponent
@endsection

@section('content')
<article>
    <div class="container">
        <div class="row">
            <p>{{ $article->body }}</p>
        </div>
    </div>
</article>
@endsection

resources/views/templates/components/_masthead.blade.php
<header class="masthead" style="background-image: url('{{ $image }}')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>{{ $title }}</h1>
                    <span class="subheading">{{ $subtitle }}</span>
                    {{ $slot }}
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/templates/default.blade.php
<!DOCTYPE html>
<html lang="en">

  @include('templates.partials._head')

  <body>

    <!-- Navigation -->
    @include('templates.partials._navigation')

    <!-- Page Header -->
    @yield('masthead')

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

          @yield('content')
          <hr>
          <!-- Pager -->
          {{-- <div class="clearfix">
            <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
          </div> --}}
        </div>
      </div>
    </div>

    <hr>

    <!-- Footer -->
    @include('templates.partials._footer')

  </body>

</html>

resources/views/templates/partials/_footer.blade.php
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{{ asset('assets/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Custom scripts for this template -->
<script src="{{ asset('assets/js/clean-blog.min.js') }}"></script>

@stack('scripts')

resources/views/templates/partials/_head.blade.php
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Secure Coding</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{{ asset('assets/vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
        rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{{ asset('assets/css/clean-blog.min.css') }}" rel="stylesheet">

</head>

resources/views/templates/partials/_navigation.blade.php
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ route('home') }}">Secure Coding</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                @if (session('email'))
                <li class="nav-item">
                        <a class="nav-link btn btn-success" href="{{ route('article.create') }}">Create Article</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-danger" href="{{ route('logout') }}">Logout</a>
                    </li>
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">Register</a>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/user/edit.blade.php
@extends('templates.default')

@section('masthead')
    @component('templates.components._masthead', [
        'image' => asset('assets/img/contact-bg.jpg'),
        'title' => 'Update Profile '. $user->name,
        'subtitle' => 'Update your Profile'
    ])

    @endcomponent
@endsection

@section('content')
    <p>Update your Profile</p>
    <form action="{{ route('profile.update') }}" name="sentMessage" id="registerForm" method="post" enctype="multipart/form-data">
        @csrf
        @method("PUT")
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Name</label>
                <input type="text" name="name" class="form-control" placeholder="Your title" id="title" required data-validation-required-message="Please enter your name." value="{{ old('name') ?? $user->name }}">
                @if ($errors->has('name'))
                    <p class="help-block text-danger">{{ $errors->first('name') }}</p>
                @endif
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Email</label>
                <input type="email" name="email" class="form-control" placeholder="Your title" id="title" required data-validation-required-message="Please enter your email." value="{{ old('email') ?? $user->email }}">
                @if ($errors->has('email'))
                    <p class="help-block text-danger">{{ $errors->first('email') }}</p>
                @endif
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Title</label>
                <input type="password" name="password" class="form-control" placeholder="Your pasword" id="title" >
                @if ($errors->has('password'))
                    <p class="help-block text-danger">{{ $errors->first('password') }}</p>
                @endif
            </div>
        </div>
        <br>
        <div id="success"></div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary" id="">Update</button>
        </div>
    </form>
@endsection

resources/views/user/show.blade.php
@extends('templates.default')

@section('masthead')
    @component('templates.components._masthead', [
        'image' => asset('assets/img/contact-bg.jpg'),
        'title' => 'Profile '  . $user->name,
        'subtitle' => 'Articles from '  . $user->name,
    ])

    @endcomponent
@endsection

@section('content')
    @foreach ($articles as $article)
    {{-- {{ dd($article)}} --}}
        <div class="post-preview">
            <a href="{{ route('article.show', $article->id) }}">
                <h2 class="post-title">
                    {{ $article->title }}
                </h2>
                <h3 class="post-subtitle">
                    {{ str_limit($article->body, 100)}}
                </h3>
            </a>
            <p class="post-meta">Posted by
            <a href="{{ route('profile.show', $article->user_id) }}">{{ $article->name }}</a>
            on {{ $article->created_at }}</p>
        </div>
        @if ($article->user_id === session('id'))
        <div class="row">
            <a href="{{ route('article.edit', $article->id) }}" class="btn btn-warning">Edit</a>
            <button id="delete" href="{{ route('article.destroy', $article->id) }}" class="btn btn-danger">Delete</button>
        </div>
        @endif
        <hr>
        <form action="" id="deleteForm" method="post">
            @csrf
            @method("DELETE")
            <input type="submit" value="" style="display:none">
        </form>
    @endforeach
@endsection

@push('scripts')
<script>



    $('button#delete').on('click', function() {
        var href = $(this).attr('href');

        document.getElementById('deleteForm').action = href;
        document.getElementById('deleteForm').submit();
    });
</script>
@endpush